theme: jekyll-theme-minimal
title: Arun Nedunchezhian
description: Passionate about applications of Deep Learning in NLP, Vision
logo: profile_pic.jpeg

twitter_username: arunn314
linkedin_username: arun-nedunchezhian-8346683b
